# Tên của workflow
name: API Test Workflow (Newman)

# Kích hoạt khi push hoặc pull request
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Định nghĩa công việc
jobs:
  api-testing:
    name: Run Postman Tests with Newman
    # Chạy trên máy ảo Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code về (code này đã chứa file .json)
      - name: 1. Check out repository
        uses: actions/checkout@v4

      # Bước 2: Khởi chạy toàn bộ hệ thống (app, db)
      # -d (detached mode) là chạy ngầm, không block terminal
      - name: 2. Start services (Docker Compose)
        run: docker compose up -d

      # Bước 3: Đợi backend sẵn sàng (rất quan trọng)
      # Lệnh này sẽ liên tục gọi /health 5 giây một lần cho đến khi thành công
      - name: 3. Wait for backend to be healthy
        run: |
          echo "Waiting for backend..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:3001/health); do
            printf '.'
            sleep 5
          done
          echo "Backend is healthy!"

      # Bước 4: Cài đặt Newman (công cụ chạy test Postman)
      - name: 4. Install Newman
        run: npm install -g newman

      # Bước 5: Chạy test!
      # ** QUAN TRỌNG: Đảm bảo tên file này đúng với tên file bạn đã lưu **
      - name: 5. Run Newman tests
        run: newman run "Mocktest.postman_collection.json" 
        # (Mình để tên trong ngoặc kép "" để phòng trường hợp bạn lưu tên là "Mocktest API.postman_collection.json")

      # Bước 6: (Luôn chạy) Dọn dẹp sau khi test xong
      # 'if: always()' đảm bảo bước này luôn chạy, kể cả khi test fail
      - name: 6. Stop services
        if: always() 
        run: docker compose down

